# =========== Experiment ===========
exp_path: ./runs
exp_name: default
device: cpu # Device to run the application on, can be either 'cpu' or 'cuda' (default: cpu)
seed: 42 # Seed for random number generators, fixing the randomness in the application (default: 42)

# =========== Parameters ===========
max_iterations: 30000
lambd: 1e-5
mu_1: 1e-7
mu_2: 1e-6
mu_3: 1e-6

# =========== Noise parameters ===========
enable_noise: False # Whether to enable noise in the application (default: False)
noise_level:  1e-1
samples: 10

# =========== Data ===========
data_path: ./data

# =========== Logging ===========
log_to_console: True # Whether to log to console during execution (default: True)
verbose: False # Whether to log detailed information (default: False)
save_logs: True # Whether to save logs (default: True)
log_level: INFO # Logging level for the application (default: INFO)